openapi: 3.0.0
x-stoplight:
  id: ptt53t0unyvnw
info:
  title: order-manager-api
  version: '1.0'
servers:
  - url: 'http://localhost:8085'
paths:
  '/users/{user_id}':
    parameters:
      - schema:
          type: string
        name: user_id
        in: path
        required: true
    get:
      summary: Get User By Id
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
    put:
      summary: Update User
      operationId: put-users-user_id
      responses:
        '201':
          description: Created
        '404':
          description: User Not Found
      description: 'Update User '
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
    delete:
      summary: Delete User
      operationId: delete-users-user_id
      responses:
        '200':
          description: OK
        '404':
          description: UserNot Found
      description: Delete User
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
  /stock/movement:
    get:
      summary: Create Stock Movement
      tags: []
      responses: {}
      operationId: get-stock-movement
      description: ''
    post:
      summary: ''
      operationId: post-stock-movement
      responses:
        '200':
          description: OK
      description: Add Items to the Stock
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: string
          description: Unique identifier for the given user.
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email
          example: user@mail.com
      required:
        - id
        - name
        - email
    ItemQuantity:
      title: ItemQuantity
      x-stoplight:
        id: bfbujt9kwkj0d
      type: object
      properties:
        item_id:
          type: string
          format: uuid
        item_quantity:
          type: integer
          minimum: 1
      required:
        - item_id
        - item_quantity
    Order:
      title: Order
      x-stoplight:
        id: esligyddn7hea
      type: object
      properties:
        id:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/ItemQuantity'
        status:
          type: string
          enum:
            - PENDING
            - COMPLETED
        created_by:
          type: string
          format: uuid
        creation_date:
          type: string
          format: date
    StockMovement:
      title: StockMovement
      x-stoplight:
        id: cf9drd4dskuka
      type: object
      properties:
        id:
          type: string
          format: uuid
        items:
          type: array
          items:
            $ref: '#/components/schemas/ItemQuantity'
        creation_date:
          type: string
          format: date
      required:
        - items
    OrderStockMovemets:
      title: OrderStockMovemets
      x-stoplight:
        id: 8dfz36i1hnpvk
      type: object
      properties:
        order_id:
          type: string
        stock_movements:
          type: array
          items:
            $ref: '#/components/schemas/Stock'
    StockMovementOrders:
      title: StockMovementOrders
      x-stoplight:
        id: qf7xf5smtqwib
      type: object
      properties:
        stock_movement_id:
          type: string
        orders:
          type: array
          items:
            $ref: '#/components/schemas/Order'
  requestBodies: {}
  parameters:
    user_id:
      name: user_id
      in: header
      required: true
      schema:
        type: string
        format: uuid
      description: 'User unique id, in UUID format'
  responses: {}
